Repository objet-team/objet-backend, pull requests merged in 2023-10, with the labels that each got.

#72 [fix] 굿즈 관련 기능 수정
  src/main/java/com/server/objet/domain/goods/GoodsController.java
  src/main/java/com/server/objet/domain/goods/GoodsService.java
  src/main/java/com/server/objet/domain/goods/dto/CartItemInfo.java
  src/main/java/com/server/objet/domain/goods/dto/GoodsDetailInfo.java
  src/main/java/com/server/objet/domain/goods/dto/GoodsInfo.java
  src/main/java/com/server/objet/domain/goods/dto/ThumbNailInfo.java
  src/main/java/com/server/objet/global/entity/Goods.java
  src/main/java/com/server/objet/global/entity/GoodsThumbNail.java
  src/main/java/com/server/objet/global/repository/GoodsThumbNailRepository.java
Labels: fix

#74 [Fix] 팔로우 여부 api 추가 & 작품 상세보기 api에 아티스트 Id 추가
  src/main/java/com/server/objet/domain/artist/ArtistController.java
  src/main/java/com/server/objet/domain/auth/AuthController.java
  src/main/java/com/server/objet/domain/follow/FollowController.java
  src/main/java/com/server/objet/domain/follow/FollowService.java
  src/main/java/com/server/objet/domain/product/ProductService.java
  src/main/java/com/server/objet/domain/product/dto/ProductDetail.java
Labels: feat, fix

#76 [feat] 장바구니 수량 변경 기능 추가
  src/main/java/com/server/objet/domain/goods/GoodsController.java
  src/main/java/com/server/objet/domain/goods/GoodsService.java
  src/main/java/com/server/objet/domain/goods/dto/CartGoodsRecount.java
  src/main/java/com/server/objet/global/entity/Cart.java
Labels: feat
